const enumExports = {
  EnumActualizacionWEB: "./EnumActualizacionWEB",
  EnumAplicacionConceptoNovedadEmpresal:
    "./EnumAplicacionConceptoNovedadEmpresal",
  EnumArchivoPlano: "./EnumArchivoPlano",
  EnumAreaTrabajo: "./EnumAreaTrabajo",
  EnumCertificadoIngresosAportesListado:
    "./EnumCertificadoIngresosAportesListado",
  EnumClaseEmpresa: "./EnumClaseEmpresa",
  EnumConceptosCertificacion: "./EnumConceptosCertificacion",
  EnumConceptosContrato: "./EnumConceptosContrato",
  EnumContinente: "./EnumContinente",
  EnumDiasSemana: "./EnumDiasSemana",
  EnumEstadoCalendario: "./EnumEstadoCalendario",
  EnumEstadoCivil: "./EnumEstadoCivil",
  EnumFormaPresentacion: "./EnumFormaPresentacion",
  EnumGrupoSanguineo: "./EnumGrupoSanguineo",
  EnumIncapacidades: "./EnumIncapacidades",
  EnumLocalizacion: "./EnumLocalizacion",
  EnumMensajes: "./EnumMensajes",
  EnumModalidadEjecucionNomina: "./EnumModalidadEjecucionNomina",
  EnumModalidadServicio: "./EnumModalidadServicio",
  EnumModulos: "./EnumModulos",
  EnumModulosNovedades: "./EnumModulosNovedades",
  EnumNE_Ambiente: "./EnumNE_Ambiente",
  EnumNE_FormaPago: "./EnumNE_FormaPago",
  EnumNE_Licencias: "./EnumNE_Licencias",
  EnumNE_Operadores: "./EnumNE_Operadores",
  EnumNE_PeriodoNomina: "./EnumNE_PeriodoNomina",
  EnumNE_Status: "./EnumNE_Status",
  EnumNE_TipoArchivo: "./EnumNE_TipoArchivo",
  EnumNE_TipoContrato: "./EnumNE_TipoContrato",
  EnumNE_TipoDocumento: "./EnumNE_TipoDocumento",
  EnumNE_TipoHora: "./EnumNE_TipoHora",
  EnumNE_TipoIncapacidad: "./EnumNE_TipoIncapacidad",
  EnumNE_TipoNota: "./EnumNE_TipoNota",
  EnumNE_TipoXML: "./EnumNE_TipoXML",
  EnumNE_Vacaciones: "./EnumNE_Vacaciones",
  EnumNivelRiesgo: "./EnumNivelRiesgo",
  EnumNovedadReteFuente: "./EnumNovedadReteFuente",
  EnumOperadores: "./EnumOperadores",
  EnumParentesco: "./EnumParentesco",
  EnumRegimenExcepcionSSS: "./EnumRegimenExcepcionSSS",
  EnumReporteComprobantesPAGO: "./EnumReporteComprobantesPAGO",
  EnumReporteComprobantesPAGOFiltros: "./EnumReporteComprobantesPAGOFiltros",
  EnumRespuestaSINO: "./EnumRespuestaSINO",
  EnumReteFuenteProcedimiento: "./EnumReteFuenteProcedimiento",
  EnumRutas: "./EnumRutas",
  EnumSemana: "./EnumSemana",
  EnumSexo: "./EnumSexo",
  EnumStatusWeb: "./EnumStatusWeb",
  EnumTiempo: "./EnumTiempo",
  EnumTiempoNovedades: "./EnumTiempoNovedades",
  EnumTipoActividad: "./EnumTipoActividad",
  EnumTipoCentroCosto: "./EnumTipoCentroCosto",
  EnumTipoConceptoMO: "./EnumTipoConceptoMO",
  EnumTipoContrato: "./EnumTipoContrato",
  EnumTipoCuenta: "./EnumTipoCuenta",
  EnumTipoCuota: "./EnumTipoCuota",
  EnumTipoHora: "./EnumTipoHora",
  EnumTipoIdentificacion: "./EnumTipoIdentificacion",
  EnumTipoIdentificacionEmbargo: "./EnumTipoIdentificacionEmbargo",
  EnumTipoInformeSegSoc: "./EnumTipoInformeSegSoc",
  EnumTipoLibretaMilitar: "./EnumTipoLibretaMilitar",
  EnumTipoLiquidacion: "./EnumTipoLiquidacion",
  EnumTipoMovimiento: "./EnumTipoMovimiento",
  EnumTipoNovedad: "./EnumTipoNovedad",
  EnumTipoNovedadSeguridadSocial: "./EnumTipoNovedadSeguridadSocial",
  EnumTipoNumeroPILA: "./EnumTipoNumeroPILA",
  EnumTipoPago: "./EnumTipoPago",
  EnumTipoPagoLiquidacion: "./EnumTipoPagoLiquidacion",
  EnumTipoPersona: "./EnumTipoPersona",
  EnumTipoPlanilla: "./EnumTipoPlanilla",
  EnumTipoReferencia: "./EnumTipoReferencia",
  EnumTipoRegimen: "./EnumTipoRegimen",
  EnumTipoRegistro: "./EnumTipoRegistro",
  EnumTipoRegistroConceptoNovedadEmpresa:
    "./EnumTipoRegistroConceptoNovedadEmpresa",
  EnumTipoRegistroHistorial: "./EnumTipoRegistroHistorial",
  EnumTipoRegistroLiquidacion: "./EnumTipoRegistroLiquidacion",
  EnumTipoServicioSeguridadSocial: "./EnumTipoServicioSeguridadSocial",
  EnumTipoTransferencia: "./EnumTipoTransferencia",
  EnumTipoTurno: "./EnumTipoTurno",
  EnumVariablesSistema: "./EnumVariablesSistema",
};

for (const [exportName, relPath] of Object.entries(enumExports)) {
  Object.defineProperty(module.exports, exportName, {
    enumerable: true,
    get() {
      return require(relPath);
    },
  });
}
